### ISSUE TITLE
浅谈 CSS 预处理器（一）：为什么要使用预处理器？

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/blog#73]
# 浅谈 CSS 预处理器（一）：为什么要使用预处理器？

> ### 前言
> 
> 你好，我是魔法哥。我是一名传统的前端开发者，我的很大一部分工作就是为各种类型的网页写 CSS，写了很多年。
> 
> 我从三年前开始接触并使用 CSS 预处理，如鱼得水，相见恨晚。因此，我感觉有必要写些文章来总结一下这方面的心得。如果你是一位还没有接触预处理器的 CSS 开发者，希望我的文章能够帮助你轻松开始！
> 
> （注：本文的示例代码均采用 Stylus 作为 CSS 预处理语言。）

## 背景

CSS 自诞生以来，基本语法和核心机制一直没有本质上的变化，它的发展几乎全是表现力层面上的提升。最开始 CSS 在网页中的作用只是辅助性的装饰，轻便易学是最大的需求；然而如今网站的复杂度已经不可同日而语，原生 CSS 已经让开发者力不从心。

当一门语言的能力不足而用户的运行环境又不支持其它选择的时候，这门语言就会沦为 “编译目标” 语言。开发者将选择另一门更高级的语言来进行开发，然后编译到底层语言以便实际运行。

于是，在前端领域，天降大任于斯人也，CSS 预处理器应运而生。而 CSS 这门古老的语言以另一种方式 “重新适应” 了网页开发的需求。

## 预处理器赋予我们的 “超能力”

简单梳理一下，CSS 预处理器为我们带来了几项重要的能力，由浅入深排列如下。（不用在意你用到了多少，无论深浅，都是获益。）

### 文件切分

页面越来越复杂，需要加载的 CSS 文件也越来越大，我们有必要把大文件切分开来，否则难以维护。传统的 CSS 文件切分方案基本上就是 CSS 原生的 `@import` 指令，或在 HTML 中加载多个 CSS 文件，这些方案通常不能满足性能要求。

CSS 预处理器扩展了 `@import` 指令的能力，通过编译环节将切分后的文件重新合并为一个大文件。这一方面解决了大文件不便维护的问题，另一方面也解决了一堆小文件在加载时的性能问题。

### 模块化

把文件切分的思路再向前推进一步，就是 “模块化”。一个大的 CSS 文件在合理切分之后，所产生的这些小文件的相互关系应该是一个树形结构。

树形的根结节一般称作 “入口文件”，树形的其它节点一般称作 “模块文件”。入口文件通常会依赖多个模块文件，各个模块文件也可能会依赖其它更末端的模块，从而构成整个树形。

以下是一个简单的示例：

```
entry.styl
 ├─ base.styl
 │   ├─ normalize.styl
 │   └─ reset.styl
 ├─ layout.styl
 │   ├─ header.styl
 │   │   └─ nav.styl
 │   └─ footer.styl
 ├─ section-foo.styl
 ├─ section-bar.styl
 └─ ...
```

（入口文件 `entry.styl` 在编译时会引入所需的模块，生成 `entry.css`，然后被页面引用。）

如果你用过其它拥有模块机制的编程语言，应该已经深有体会，模块化是一种非常好的代码组织方式，是开发者设计代码结构的重要手段。模块可以很清晰地实现代码的分层、复用和依赖管理，让 CSS 的开发过程也能享受到现代程序开发的便利。

### 选择符嵌套

选择符嵌套是文件内部的代码组织方式，它可以让一系列相关的规则呈现出层级关系。在以前，如果要达到这个目的，我们只能这样写：

```css
.nav {margin: auto /* 水平居中 */; width: 1000px; color: #333;}
    .nav li {float: left /* 水平排列 */; width: 100px;}
        .nav li a {display: block; text-decoration: none;}
```

这种写法需要我们手工维护缩进关系，当上级选择符发生变化时，所有相关的下级选择符都要修改；此外，把每条规则写成一行也不易阅读，为单条声明写注释也很尴尬（只能插在声明之间了）。

在 CSS 预处理语言中，嵌套语法可以很容易地表达出规则之间的层级关系，为单条声明写注释也很清晰易读：

```stylus
.nav
    margin: auto  // 水平居中
    width: 1000px
    color: #333
    li
        float: left  // 水平排列
        width: 100px
        a
            display: block
            text-decoration: none
```

### 变量

在变更出现之前，CSS 中的所有属性值都是 “幻数”。你不知道这个值是怎么来的、它的什么样的意义。有了变量之后，我们就可以给这些 “幻数” 起个名字了，便于记忆、阅读和理解。

接下来我们会发现，当某个特定的值在多处用到时，变量就是一种简单而有效的抽象方式，可以把这种重复消灭掉，让你的代码更加 DRY。

我们来比较一下以下两段代码：

```css
/* 原生 CSS 代码 */
strong {
	color: #ff4466;
	font-weight: bold;
}

/* ... */

.notice {
	color: #ff4466;
}
```

```stylus
// 用 Stylus 来写
$color-primary = #ff4466

strong
	color: $color-primary
	font-weight: bold

/* ... */

.notice
	color: $color-primary
```

你可能已经意识到了，变量让开发者更容易实现网站视觉风格的统一，也让 “换肤” 这样的需求变得更加轻松易行。

### 运算

光有变量还是不够的，我们还需要有运算。如果说变量让值有了意义，那么运算则可以让值和值建立关联。有些属性的值其实跟其它属性的值是紧密相关的，CSS 语法无法表达这层关系；而在预处理语言中，我们可以用变量和表达式来呈现这种关系。

举个例子，我们需要让一个容器最多只显示三行文字，在以前我们通常是这样写的：

```css
.wrapper {
	overflow-y: hidden;
	line-height: 1.5;
	max-height: 4.5em;  /* = 1.5 x 3 */
}
```

大家可以发现，我们只能用注释来表达 `max-height` 的值是怎么来的，而且注释中 `3` 这样的值也是幻数，还需要进一步解释。未来当行高或行数发生变化的时候，`max-height` 的值和注释中的算式也需要同步更新，维护起来很不方便。

接下来我们用预处理语言来改良一下：

```stylus
.wrapper
	$max-lines = 3
	$line-height = 1.5

	overflow-y: hidden
	line-height: $line-height
	max-height: unit($line-height * $max-lines, 'em')
```

乍一看，代码行数似乎变多了，但代码的意图却更加清楚了——不需要任何注释就把整件事情说清楚了。在后期维护时，只要修改那两个变量就可以了。

值得一提的是，这种写法还带来另一个好处。`$line-height` 这个变量可以是 `.wrapper` 自己定义的局部变量（比如上面那段代码），也可以从更上层的作用域获取：

```stylus
$line-height = 1.5  // 全局统一行高

body
	line-height: $line-height

.wrapper
	$max-lines = 3

	max-height: unit($line-height * $max-lines, 'em')
	overflow-y: hidden
```

这意味着 `.wrapper` 可以向祖先继承行高，而不需要为这个 “只显示三行” 的需求把自己的行高写死。有了运算，我们就有能力表达属性与属性之间的关联，它令我们的代码更加灵活、更加 DRY。

### 函数

把常用的运算操作抽象出来，我们就得到了函数。

开发者可以自定义函数，预处理器自己也内置了大量的函数。最常用的内置函数应该就是颜色的运算函数了吧！有了它们，我们甚至都不需要打开 Photoshop 来调色，就可以得到某个颜色的同色系变种了。

举个例子，我们要给一个按钮添加鼠标悬停效果，而最简单的悬停效果就是让按钮的颜色加深一些。我们写出的 CSS 代码可能是这样的：

```css
.button {
	background-color: #ff4466;
}
.button:hover {
	background-color: #f57900;
}
```

我相信即使是最资深的视觉设计师，也很难分清 `#ff4466` 和 `#f57900` 这两种颜色到底有什么关联。而如果我们的代码是用预处理语言来写的，那事情就直观多了：

```stylus
.button
	$color = #ff9833

	background-color: $color
	&:hover
		background-color: darken($color, 20%)
```

此外，预处理器的函数往往还支持默认参数、具名实参、`arguments` 对象等高级功能，内部还可以设置条件分支，可以满足复杂的逻辑需求。

### Mixin

Mixin 是 CSS 预处理器提供的又一项实用功能。Mixin 的形态和用法跟函数十分类似——先定义，然后在需要的地方调用，在调用时可以接受参数。它与函数的不同之处在于…………

……

……

***

> 完整文章已收录到 “CSS魔法” 微信公众号，扫码立即订阅：
>
> ![weixin-qrcode](https://cloud.githubusercontent.com/assets/1231359/13040994/04966808-d3ee-11e5-8eb5-7e3bf8767f4e.png)

***

&copy; Creative Commons BY-NC-ND 4.0 &nbsp; | &nbsp; [我要订阅](http://www.cssmagic.net/blog/subscribe) &nbsp; | &nbsp; [我要打赏](http://www.cssmagic.net/blog/donate)
